<?php
/**
 * VolunteerHours Module - Variable Definitions (Simplified)
 * 
 * This file defines the database table structure and field definitions
 * for the VolunteerHours module.
 * 
 * @package SuiteCRM
 * @subpackage YouthSportsLeague
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$dictionary['VolunteerHours'] = array(
    'table' => 'volunteerhours',
    'audited' => true,
    'unified_search' => true,
    'full_text_search' => true,
    'duplicate_merge' => true,
    'comment' => 'Volunteer Hours and Recognition Tracker',
    'fields' => array(
        // Standard SugarBean fields
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier',
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => true,
            'full_text_search' => array('boost' => 3),
            'required' => false,
            'importable' => 'false',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'size' => '20',
            'comment' => 'Entry name for this volunteer hours record (auto-generated)',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'group' => 'modified_by_name',
            'dbType' => 'id',
            'reportable' => true,
            'comment' => 'User who last modified record',
            'massupdate' => false,
        ),
        'modified_by_name' => array(
            'name' => 'modified_by_name',
            'vname' => 'LBL_MODIFIED_NAME',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'rname' => 'user_name',
            'table' => 'users',
            'id_name' => 'modified_user_id',
            'module' => 'Users',
            'link' => 'modified_user_link',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
            'group' => 'created_by_name',
            'comment' => 'User who created record',
            'massupdate' => false,
        ),
        'created_by_name' => array(
            'name' => 'created_by_name',
            'vname' => 'LBL_CREATED',
            'type' => 'relate',
            'reportable' => false,
            'link' => 'created_by_link',
            'rname' => 'user_name',
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'created_by',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
            'importable' => 'false',
            'massupdate' => false,
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => 6,
            'cols' => 80,
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'comment' => 'Record deletion indicator',
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'group' => 'assigned_user_name',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'reportable' => true,
            'isnull' => 'false',
            'dbType' => 'id',
            'audited' => true,
            'comment' => 'User ID assigned to record',
            'duplicate_merge' => 'disabled',
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'rname' => 'user_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
        ),

        // Custom Fields for Volunteer Hours - SAFE RELATE FIELDS
        'volunteer_id_c' => array(
            'name' => 'volunteer_id_c',
            'vname' => 'LBL_VOLUNTEER_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'comment' => 'ID of the volunteer (Contact)',
        ),
        'volunteer_name_c' => array(
            'name' => 'volunteer_name_c',
            'vname' => 'LBL_VOLUNTEER_NAME',
            'rname' => 'name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'contacts',
            'id_name' => 'volunteer_id_c',
            'module' => 'Contacts',
            'duplicate_merge' => 'disabled',
            'studio' => 'visible',
            'massupdate' => false,
            'required' => false,
            'comment' => 'Name of the volunteer',
        ),
        'activity_date_c' => array(
            'name' => 'activity_date_c',
            'vname' => 'LBL_ACTIVITY_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'required' => true,
            'comment' => 'Date when volunteer activity occurred',
        ),
        'hours_logged_c' => array(
            'name' => 'hours_logged_c',
            'vname' => 'LBL_HOURS_LOGGED',
            'type' => 'decimal',
            'len' => '5,2',
            'precision' => '2',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'required' => true,
            'comment' => 'Number of hours volunteered',
        ),
        'activity_type_c' => array(
            'name' => 'activity_type_c',
            'vname' => 'LBL_ACTIVITY_TYPE',
            'type' => 'enum',
            'options' => 'volunteer_activity_type_list',
            'len' => 50,
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'comment' => 'Type of volunteer activity performed',
        ),
        'program_name_c' => array(
            'name' => 'program_name_c',
            'vname' => 'LBL_PROGRAM_NAME',
            'type' => 'enum',
            'options' => 'volunteer_sport_programs_list',
            'len' => 255,
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'comment' => 'Name of the sport program',
        ),
        'activity_description_c' => array(
            'name' => 'activity_description_c',
            'vname' => 'LBL_ACTIVITY_DESCRIPTION',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'rows' => 4,
            'cols' => 80,
            'comment' => 'Description of volunteer activity',
        ),
        'approval_status_c' => array(
            'name' => 'approval_status_c',
            'vname' => 'LBL_APPROVAL_STATUS',
            'type' => 'enum',
            'options' => 'volunteer_hours_approval_status_list',
            'len' => 50,
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'comment' => 'Approval status of volunteer hours',
        ),
        'approved_by_c' => array(
            'name' => 'approved_by_c',
            'vname' => 'LBL_APPROVED_BY',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'comment' => 'User who approved the hours',
        ),
        'approved_date_c' => array(
            'name' => 'approved_date_c',
            'vname' => 'LBL_APPROVED_DATE',
            'type' => 'datetime',
            'massupdate' => 0,
            'no_default' => false,
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'comment' => 'Date and time when hours were approved',
        ),
    ),
    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
    'links' => array(
        'volunteer_contact' => array(
            'name' => 'volunteer_contact',
            'type' => 'one',
            'relationship' => '',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'source' => 'non-db',
            'vname' => 'LBL_VOLUNTEER_CONTACT',
        ),
    ),
); 