<?php
/**
 * VolunteerHours Module - Variable Definitions
 * 
 * This file defines the field structure and relationships for the
 * VolunteerHours module in the Youth Sports League CRM.
 * 
 * @package SuiteCRM
 * @subpackage YouthSportsLeague
 * @author Youth Sports League CRM
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$dictionary['VolunteerHours'] = array(
    'table' => 'volunteerhours',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(
        // Standard SugarBean fields
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier',
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => 150,
            'unified_search' => true,
            'full_text_search' => array('boost' => 3),
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => false,
            'reportable' => true,
            'size' => '20',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'group' => 'modified_by_name',
            'dbType' => 'id',
            'reportable' => true,
            'comment' => 'User who last modified record',
            'massupdate' => false,
        ),
        'modified_by_name' => array(
            'name' => 'modified_by_name',
            'vname' => 'LBL_MODIFIED_NAME',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'rname' => 'user_name',
            'table' => 'users',
            'id_name' => 'modified_user_id',
            'module' => 'Users',
            'link' => 'modified_user_link',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
            'group' => 'created_by_name',
            'comment' => 'User who created record',
            'massupdate' => false,
        ),
        'created_by_name' => array(
            'name' => 'created_by_name',
            'vname' => 'LBL_CREATED',
            'type' => 'relate',
            'reportable' => false,
            'link' => 'created_by_link',
            'rname' => 'user_name',
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'created_by',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
            'importable' => 'false',
            'massupdate' => false,
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => 6,
            'cols' => 80,
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'comment' => 'Record deletion indicator',
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'group' => 'assigned_user_name',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'reportable' => true,
            'isnull' => 'false',
            'dbType' => 'id',
            'audited' => true,
            'comment' => 'User ID assigned to record',
            'duplicate_merge' => 'disabled',
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'rname' => 'user_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
        ),

        // Custom Fields for Volunteer Hours
        'volunteer_id_c' => array(
            'name' => 'volunteer_id_c',
            'vname' => 'LBL_VOLUNTEER_ID',
            'type' => 'relate',
            'link' => 'volunteerhours_contacts',
            'table' => 'contacts',
            'isnull' => 'true',
            'module' => 'Contacts',
            'dbType' => 'id',
            'reportable' => true,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'id_name' => 'volunteer_id_c',
            'ext2' => 'Contacts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'required' => true,
            'comment' => 'ID of the volunteer (Contact)',
        ),
        'volunteer_name_c' => array(
            'name' => 'volunteer_name_c',
            'vname' => 'LBL_VOLUNTEER_NAME',
            'type' => 'relate',
            'link' => 'volunteerhours_contacts',
            'table' => 'contacts',
            'isnull' => 'true',
            'module' => 'Contacts',
            'rname' => 'name',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'id_name' => 'volunteer_id_c',
            'ext2' => 'Contacts',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'source' => 'non-db',
        ),
        'activity_date_c' => array(
            'name' => 'activity_date_c',
            'vname' => 'LBL_ACTIVITY_DATE',
            'type' => 'date',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'required' => true,
            'comment' => 'Date when volunteer activity occurred',
        ),
        'hours_logged_c' => array(
            'name' => 'hours_logged_c',
            'vname' => 'LBL_HOURS_LOGGED',
            'type' => 'decimal',
            'len' => '5,2',
            'precision' => '2',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'required' => true,
            'comment' => 'Number of hours volunteered',
        ),
        'activity_type_c' => array(
            'name' => 'activity_type_c',
            'vname' => 'LBL_ACTIVITY_TYPE',
            'type' => 'enum',
            'options' => 'volunteer_activity_type_list',
            'len' => 100,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'comment' => 'Type of volunteer activity performed',
        ),
        'sport_program_id_c' => array(
            'name' => 'sport_program_id_c',
            'vname' => 'LBL_SPORT_PROGRAM_ID',
            'type' => 'relate',
            'link' => 'volunteerhours_sportprograms',
            'table' => 'sportprograms',
            'isnull' => 'true',
            'module' => 'SportPrograms',
            'dbType' => 'id',
            'reportable' => true,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'id_name' => 'sport_program_id_c',
            'ext2' => 'SportPrograms',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'comment' => 'ID of the sport program',
        ),
        'sport_program_name_c' => array(
            'name' => 'sport_program_name_c',
            'vname' => 'LBL_SPORT_PROGRAM_NAME',
            'type' => 'relate',
            'link' => 'volunteerhours_sportprograms',
            'table' => 'sportprograms',
            'isnull' => 'true',
            'module' => 'SportPrograms',
            'rname' => 'name',
            'reportable' => false,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'id_name' => 'sport_program_id_c',
            'ext2' => 'SportPrograms',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'source' => 'non-db',
        ),
        'activity_description_c' => array(
            'name' => 'activity_description_c',
            'vname' => 'LBL_ACTIVITY_DESCRIPTION',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => 4,
            'cols' => 80,
            'comment' => 'Description of volunteer activity',
        ),
        'approval_status_c' => array(
            'name' => 'approval_status_c',
            'vname' => 'LBL_APPROVAL_STATUS',
            'type' => 'enum',
            'options' => 'volunteer_hours_approval_status_list',
            'len' => 50,
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'default' => 'pending',
            'comment' => 'Approval status of volunteer hours',
        ),
        'approved_by_c' => array(
            'name' => 'approved_by_c',
            'vname' => 'LBL_APPROVED_BY',
            'type' => 'relate',
            'link' => 'volunteerhours_users',
            'table' => 'users',
            'isnull' => 'true',
            'module' => 'Users',
            'dbType' => 'id',
            'reportable' => true,
            'side' => 'right',
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'hideacl' => true,
            'id_name' => 'approved_by_c',
            'ext2' => 'Users',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
            'comment' => 'User who approved the hours',
        ),
        'approved_date_c' => array(
            'name' => 'approved_date_c',
            'vname' => 'LBL_APPROVED_DATE',
            'type' => 'datetime',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'comment' => 'Date when hours were approved',
        ),
    ),

    'relationships' => array(
        'volunteerhours_contacts' => array(
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'volunteer_id_c',
            'relationship_type' => 'one-to-many',
        ),
        'volunteerhours_sportprograms' => array(
            'lhs_module' => 'SportPrograms',
            'lhs_table' => 'sportprograms',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'sport_program_id_c',
            'relationship_type' => 'one-to-many',
        ),
        'volunteerhours_users' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'approved_by_c',
            'relationship_type' => 'one-to-many',
        ),
        'volunteerhours_assigned_user' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'assigned_user_id',
            'relationship_type' => 'one-to-many',
        ),
        'volunteerhours_modified_user' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'modified_user_id',
            'relationship_type' => 'one-to-many',
        ),
        'volunteerhours_created_by' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'VolunteerHours',
            'rhs_table' => 'volunteerhours',
            'rhs_key' => 'created_by',
            'relationship_type' => 'one-to-many',
        ),
    ),

    'links' => array(
        'volunteerhours_contacts' => array(
            'name' => 'volunteerhours_contacts',
            'type' => 'link',
            'relationship' => 'volunteerhours_contacts',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'source' => 'non-db',
            'vname' => 'LBL_VOLUNTEER',
        ),
        'volunteerhours_sportprograms' => array(
            'name' => 'volunteerhours_sportprograms',
            'type' => 'link',
            'relationship' => 'volunteerhours_sportprograms',
            'module' => 'SportPrograms',
            'bean_name' => 'SportPrograms',
            'source' => 'non-db',
            'vname' => 'LBL_SPORT_PROGRAM',
        ),
        'volunteerhours_users' => array(
            'name' => 'volunteerhours_users',
            'type' => 'link',
            'relationship' => 'volunteerhours_users',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'vname' => 'LBL_APPROVED_BY',
        ),
        'assigned_user_link' => array(
            'name' => 'assigned_user_link',
            'type' => 'link',
            'relationship' => 'volunteerhours_assigned_user',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'vname' => 'LBL_ASSIGNED_TO',
        ),
        'modified_user_link' => array(
            'name' => 'modified_user_link',
            'type' => 'link',
            'relationship' => 'volunteerhours_modified_user',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'vname' => 'LBL_MODIFIED_BY',
        ),
        'created_by_link' => array(
            'name' => 'created_by_link',
            'type' => 'link',
            'relationship' => 'volunteerhours_created_by',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
            'vname' => 'LBL_CREATED_BY',
        ),
    ),

    'indices' => array(
        array(
            'name' => 'idx_volunteerhours_volunteer_id',
            'type' => 'index',
            'fields' => array('volunteer_id_c'),
        ),
        array(
            'name' => 'idx_volunteerhours_activity_date',
            'type' => 'index',
            'fields' => array('activity_date_c'),
        ),
        array(
            'name' => 'idx_volunteerhours_program_id',
            'type' => 'index',
            'fields' => array('sport_program_id_c'),
        ),
        array(
            'name' => 'idx_volunteerhours_approval_status',
            'type' => 'index',
            'fields' => array('approval_status_c'),
        ),
    ),

    'optimistic_locking' => true,
    'unified_search' => true,
); 