<?php
/**
 * BackgroundChecks Module - Variable Definitions
 * 
 * This file defines the field structure and relationships for the
 * BackgroundChecks module in the Youth Sports League CRM.
 * 
 * @package SuiteCRM
 * @subpackage YouthSportsLeague
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$dictionary['BackgroundChecks'] = array(
    'table' => 'background_checks',
    'audited' => true,
    'unified_search' => true,
    'full_text_search' => true,
    'unified_search_default_enabled' => true,
    'duplicate_merge' => true,
    'comment' => 'Background check tracking for youth sports league volunteers',
    'fields' => array(
        // Standard SugarBean Fields
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier',
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => 255,
            'unified_search' => true,
            'full_text_search' => array('boost' => 3),
            'required' => false,
            'importable' => 'false',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '3',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => 'Auto-generated name for the background check record',
            'help' => 'Auto-generated name for the background check record',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'group' => 'modified_by_name',
            'dbType' => 'id',
            'reportable' => true,
            'comment' => 'User who last modified record',
            'massupdate' => false,
        ),
        'modified_by_name' => array(
            'name' => 'modified_by_name',
            'vname' => 'LBL_MODIFIED_NAME',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'rname' => 'user_name',
            'table' => 'users',
            'id_name' => 'modified_user_id',
            'module' => 'Users',
            'link' => 'modified_user_link',
            'duplicate_merge' => 'disabled',
            'massupdate' => false,
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbType' => 'id',
            'group' => 'created_by_name',
            'comment' => 'User who created record',
            'massupdate' => false,
        ),
        'created_by_name' => array(
            'name' => 'created_by_name',
            'vname' => 'LBL_CREATED',
            'type' => 'relate',
            'reportable' => false,
            'link' => 'created_by_link',
            'rname' => 'user_name',
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'created_by',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
            'importable' => 'false',
            'massupdate' => false,
        ),
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'rows' => 6,
            'cols' => 80,
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'comment' => 'Record deletion indicator',
        ),
        'assigned_user_id' => array(
            'name' => 'assigned_user_id',
            'rname' => 'user_name',
            'id_name' => 'assigned_user_id',
            'vname' => 'LBL_ASSIGNED_TO_ID',
            'group' => 'assigned_user_name',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'reportable' => true,
            'isnull' => 'false',
            'dbType' => 'id',
            'audited' => true,
            'comment' => 'User ID assigned to record',
            'duplicate_merge' => 'disabled',
        ),
        'assigned_user_name' => array(
            'name' => 'assigned_user_name',
            'link' => 'assigned_user_link',
            'vname' => 'LBL_ASSIGNED_TO_NAME',
            'rname' => 'user_name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'users',
            'id_name' => 'assigned_user_id',
            'module' => 'Users',
            'duplicate_merge' => 'disabled',
        ),

        // Custom Fields for Background Checks
        'volunteer_id_c' => array(
            'name' => 'volunteer_id_c',
            'vname' => 'LBL_VOLUNTEER_ID',
            'type' => 'id',
            'dbType' => 'id',
            'reportable' => true,
            'massupdate' => false,
            'duplicate_merge' => 'disabled',
            'comment' => 'ID of the volunteer (Contact)',
        ),
        'volunteer_name_c' => array(
            'name' => 'volunteer_name_c',
            'vname' => 'LBL_VOLUNTEER_NAME',
            'rname' => 'name',
            'type' => 'relate',
            'reportable' => false,
            'source' => 'non-db',
            'table' => 'contacts',
            'id_name' => 'volunteer_id_c',
            'module' => 'Contacts',
            'duplicate_merge' => 'disabled',
            'studio' => 'visible',
            'massupdate' => false,
            'required' => true,
            'comment' => 'Name of the volunteer',
        ),
        'background_check_type_c' => array(
            'name' => 'background_check_type_c',
            'vname' => 'LBL_BACKGROUND_CHECK_TYPE',
            'type' => 'enum',
            'options' => 'background_check_type_list',
            'len' => 50,
            'comment' => 'Type of background check performed',
            'merge_filter' => 'disabled',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'studio' => 'visible',
        ),
        'check_date_c' => array(
            'name' => 'check_date_c',
            'vname' => 'LBL_CHECK_DATE',
            'type' => 'date',
            'comment' => 'Date when the background check was performed',
            'merge_filter' => 'disabled',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'expiration_date_c' => array(
            'name' => 'expiration_date_c',
            'vname' => 'LBL_EXPIRATION_DATE',
            'type' => 'date',
            'comment' => 'Date when the background check expires',
            'merge_filter' => 'disabled',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'required' => true,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'status_c' => array(
            'name' => 'status_c',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'background_check_status_list',
            'len' => 50,
            'comment' => 'Manual status of the background check',
            'merge_filter' => 'disabled',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'required' => false,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'studio' => 'visible',
        ),
        'auto_calculated_status_c' => array(
            'name' => 'auto_calculated_status_c',
            'vname' => 'LBL_AUTO_CALCULATED_STATUS',
            'type' => 'enum',
            'options' => 'background_check_status_list',
            'len' => 50,
            'comment' => 'Auto-calculated status based on expiration date',
            'merge_filter' => 'disabled',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'required' => false,
            'importable' => 'false',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'studio' => 'visible',
        ),
        'provider_c' => array(
            'name' => 'provider_c',
            'vname' => 'LBL_PROVIDER',
            'type' => 'varchar',
            'len' => 255,
            'comment' => 'Background check provider/company',
            'merge_filter' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'required' => false,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'certificate_number_c' => array(
            'name' => 'certificate_number_c',
            'vname' => 'LBL_CERTIFICATE_NUMBER',
            'type' => 'varchar',
            'len' => 100,
            'comment' => 'Certificate or reference number',
            'merge_filter' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'required' => false,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'cost_c' => array(
            'name' => 'cost_c',
            'vname' => 'LBL_COST',
            'type' => 'currency',
            'comment' => 'Cost of the background check',
            'merge_filter' => 'disabled',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'required' => false,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
        ),
        'notes_c' => array(
            'name' => 'notes_c',
            'vname' => 'LBL_NOTES',
            'type' => 'text',
            'comment' => 'Additional notes about the background check',
            'rows' => 4,
            'cols' => 80,
        ),
        'renewal_reminder_sent_c' => array(
            'name' => 'renewal_reminder_sent_c',
            'vname' => 'LBL_RENEWAL_REMINDER_SENT',
            'type' => 'bool',
            'default' => '0',
            'comment' => 'Whether renewal reminder has been sent',
            'reportable' => true,
            'audited' => false,
            'massupdate' => false,
            'importable' => 'false',
        ),
    ),
    'relationships' => array(
        'background_checks_contacts' => array(
            'lhs_module' => 'Contacts',
            'lhs_table' => 'contacts',
            'lhs_key' => 'id',
            'rhs_module' => 'BackgroundChecks',
            'rhs_table' => 'background_checks',
            'rhs_key' => 'volunteer_id_c',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'links' => array(
        'volunteer_contact' => array(
            'name' => 'volunteer_contact',
            'type' => 'one',
            'relationship' => '',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'source' => 'non-db',
            'vname' => 'LBL_VOLUNTEER_CONTACT',
        ),
    ),
);

VardefManager::createVardef('BackgroundChecks', 'BackgroundChecks', array('basic', 'assignable', 'security_groups')); 