<?php
/**
 * Feature 3: Basic Incident Reporting
 * Variable definitions for the IncidentReporting module
 * 
 * Defines the database table structure and field properties for safety incidents.
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$dictionary['IncidentReporting'] = array(
    'table' => 'safety_incidents',
    'audited' => true,
    'unified_search' => true,
    'full_text_search' => true,
    'unified_search_default_enabled' => true,
    'duplicate_merge' => true,
    'comment' => 'Safety incidents tracking for youth sports league',
    'fields' => array(
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
            'comment' => 'Unique identifier',
            'inline_edit' => false,
        ),
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'dbtype' => 'varchar',
            'len' => 255,
            'unified_search' => true,
            'full_text_search' => array('boost' => 3),
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'comment' => 'Incident name/title',
        ),
        'date_entered' => array(
            'name' => 'date_entered',
            'vname' => 'LBL_DATE_ENTERED',
            'type' => 'datetime',
            'group' => 'created_by_name',
            'comment' => 'Date record created',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'date_modified' => array(
            'name' => 'date_modified',
            'vname' => 'LBL_DATE_MODIFIED',
            'type' => 'datetime',
            'group' => 'modified_by_name',
            'comment' => 'Date record last modified',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'created_by' => array(
            'name' => 'created_by',
            'rname' => 'user_name',
            'id_name' => 'created_by',
            'vname' => 'LBL_CREATED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbtype' => 'id',
            'group' => 'created_by_name',
            'comment' => 'User who created record',
            'massupdate' => false,
        ),
        'modified_user_id' => array(
            'name' => 'modified_user_id',
            'rname' => 'user_name',
            'id_name' => 'modified_user_id',
            'vname' => 'LBL_MODIFIED',
            'type' => 'assigned_user_name',
            'table' => 'users',
            'isnull' => 'false',
            'dbtype' => 'id',
            'group' => 'modified_by_name',
            'comment' => 'User who last modified record',
            'massupdate' => false,
        ),
        'deleted' => array(
            'name' => 'deleted',
            'vname' => 'LBL_DELETED',
            'type' => 'bool',
            'default' => '0',
            'reportable' => false,
            'comment' => 'Record deletion indicator',
        ),
        
        // Incident-specific fields
        'incident_date' => array(
            'name' => 'incident_date',
            'vname' => 'LBL_INCIDENT_DATE',
            'type' => 'date',
            'required' => true,
            'comment' => 'Date when the incident occurred',
            'importable' => 'required',
            'enable_range_search' => true,
        ),
        'incident_time' => array(
            'name' => 'incident_time',
            'vname' => 'LBL_INCIDENT_TIME',
            'type' => 'time',
            'comment' => 'Time when the incident occurred',
        ),
        'program_name' => array(
            'name' => 'program_name',
            'vname' => 'LBL_PROGRAM_NAME',
            'type' => 'varchar',
            'len' => 255,
            'comment' => 'Name of the sports program where incident occurred',
        ),
        'child_name' => array(
            'name' => 'child_name',
            'vname' => 'LBL_CHILD_NAME',
            'type' => 'varchar',
            'len' => 255,
            'comment' => 'Name of the child involved in the incident',
        ),
        'child_age' => array(
            'name' => 'child_age',
            'vname' => 'LBL_CHILD_AGE',
            'type' => 'int',
            'comment' => 'Age of the child involved',
        ),
        'incident_type' => array(
            'name' => 'incident_type',
            'vname' => 'LBL_INCIDENT_TYPE',
            'type' => 'enum',
            'options' => 'incident_type_list',
            'len' => 50,
            'comment' => 'Type/category of the incident',
            'required' => true,
        ),
        'severity_level' => array(
            'name' => 'severity_level',
            'vname' => 'LBL_SEVERITY_LEVEL',
            'type' => 'enum',
            'options' => 'severity_level_list',
            'len' => 20,
            'comment' => 'Severity level of the incident',
            'required' => true,
        ),
        'incident_description' => array(
            'name' => 'incident_description',
            'vname' => 'LBL_INCIDENT_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Detailed description of what happened',
            'rows' => 4,
            'cols' => 60,
        ),
        'immediate_action' => array(
            'name' => 'immediate_action',
            'vname' => 'LBL_IMMEDIATE_ACTION',
            'type' => 'text',
            'comment' => 'Immediate action taken in response to the incident',
            'rows' => 3,
            'cols' => 60,
        ),
        'incident_status' => array(
            'name' => 'incident_status',
            'vname' => 'LBL_INCIDENT_STATUS',
            'type' => 'enum',
            'options' => 'incident_status_list',
            'len' => 20,
            'default' => 'reported',
            'comment' => 'Current status of the incident',
        ),
        'reporter_name' => array(
            'name' => 'reporter_name',
            'vname' => 'LBL_REPORTER_NAME',
            'type' => 'varchar',
            'len' => 255,
            'comment' => 'Name of the person reporting the incident',
        ),
        'reporter_role' => array(
            'name' => 'reporter_role',
            'vname' => 'LBL_REPORTER_ROLE',
            'type' => 'enum',
            'options' => 'reporter_role_list',
            'len' => 50,
            'comment' => 'Role of the person reporting the incident',
        ),
        'medical_attention' => array(
            'name' => 'medical_attention',
            'vname' => 'LBL_MEDICAL_ATTENTION',
            'type' => 'bool',
            'default' => '0',
            'comment' => 'Whether medical attention was required',
        ),
        'parent_notified' => array(
            'name' => 'parent_notified',
            'vname' => 'LBL_PARENT_NOTIFIED',
            'type' => 'bool',
            'default' => '0',
            'comment' => 'Whether parents have been notified',
        ),
        'followup_required' => array(
            'name' => 'followup_required',
            'vname' => 'LBL_FOLLOWUP_REQUIRED',
            'type' => 'bool',
            'default' => '0',
            'comment' => 'Whether follow-up action is required',
        ),
        'followup_notes' => array(
            'name' => 'followup_notes',
            'vname' => 'LBL_FOLLOWUP_NOTES',
            'type' => 'text',
            'comment' => 'Notes about follow-up actions needed or taken',
            'rows' => 3,
            'cols' => 60,
        ),
    ),
    'indices' => array(
        array(
            'name' => 'incident_reporting_pk',
            'type' => 'primary',
            'fields' => array('id'),
        ),
        array(
            'name' => 'idx_incident_date',
            'type' => 'index',
            'fields' => array('incident_date'),
        ),
        array(
            'name' => 'idx_incident_type',
            'type' => 'index',
            'fields' => array('incident_type'),
        ),
        array(
            'name' => 'idx_severity_level',
            'type' => 'index',
            'fields' => array('severity_level'),
        ),
        array(
            'name' => 'idx_incident_status',
            'type' => 'index',
            'fields' => array('incident_status'),
        ),
    ),
); 